"""empty message

Revision ID: 148aafadad85
Revises: 4c04048f13b2
Create Date: 2021-12-20 23:23:00.920610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148aafadad85'
down_revision = '4c04048f13b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'updated_at')
    op.drop_column('account', 'created_at')
    # ### end Alembic commands ###
