"""empty message

Revision ID: 75d20b727122
Revises: 467074e39611
Create Date: 2021-12-30 07:21:36.347934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75d20b727122'
down_revision = '467074e39611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('roles', postgresql.ARRAY(sa.String(length=32)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'roles')
    # ### end Alembic commands ###
