"""empty message

Revision ID: a85b556421fd
Revises: 61cdaa5a28a4
Create Date: 2021-12-19 22:17:48.853370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a85b556421fd'
down_revision = '61cdaa5a28a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_type', sa.Enum('_CONSUMER', '_VENDOR', name='accounttype'), nullable=True))
    op.drop_column('account', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('type', postgresql.ENUM('_CONSUMER', '_VENDOR', name='accounttype'), autoincrement=False, nullable=True))
    op.drop_column('account', 'account_type')
    # ### end Alembic commands ###
