"""empty message

Revision ID: 10798d868550
Revises:
Create Date: 2022-02-06 10:23:54.442452

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision = '10798d868550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('address_line_1', sa.String(length=64), nullable=True),
    sa.Column('address_line_2', sa.String(length=32), nullable=True),
    sa.Column('address_line_3', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('employee_count_range', sa.Enum('_1_TO_4', '_5_TO_9', '_10_TO_19', '_20_TO_49', '_50_TO_99', '_100_TO_249', '_250_TO_499', '_500_TO_999', '_1000PLUS', name='employeecountrange'), nullable=True),
    sa.Column('state_tax_id', sa.String(length=16), nullable=True),
    sa.Column('state_registered', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_tax_id_verified', sa.Boolean(), nullable=True),
    sa.Column('key_products', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('key_services', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_company', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=8), nullable=True),
    sa.Column('state_province', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('yearly_revenue_range', sa.Enum('_U500K', '_500K_TO_999K', '_1MTOU2P5M', '_2P5MTOU5M', '_5MTOU10M', '_10MTOU100M', '_100MTOU500M', '_500MTOU1B', '_1BPLUS', name='yearlyrevenuerange'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('state_tax_id'),
    sa.UniqueConstraint('website')
    )
    account_table = op.create_table('account',
    sa.Column('account_type', sa.Enum('_CNS', '_VND', name='accounttype'), nullable=True),
    sa.Column('company_profile_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('given_names', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('sub', sa.String(length=64), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('surnames', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sub')
    )
    # ### end Alembic commands ###

    # Seed accounts
    op.bulk_insert(
        account_table,
        [
            {
                'email': 'vrep@vmstest.com',
                'sub': 'auth0|61ff498943fb670069baefbd',
                'account_type': '_VND',
                'roles': ['_VND_REP'],
                'created_at': datetime.now(),
                'updated_at': datetime.now()
            },
            {
                'email': 'vpub@vmstest.com',
                'sub': 'auth0|61545633ff86f6006a3241ca',
                'account_type': '_VND',
                'roles': ['_VND_PUB'],
                'created_at': datetime.now(),
                'updated_at': datetime.now()
            },
            {
                'email': 'crep@vmstest.com',
                'sub': 'auth0|6154557aff86f6006a32419c',
                'account_type': '_CNS',
                'roles': ['_CNS_REP'],
                'created_at': datetime.now(),
                'updated_at': datetime.now()
            },
            {
                'email': 'cpub@vmstest.com',
                'sub': 'auth0|615455a8fe39bb00691e01a3',
                'account_type': '_CNS',
                'roles': ['_CNS_PUB'],
                'created_at': datetime.now(),
                'updated_at': datetime.now()
            },
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
